---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/table_reasons/table_reasons.xlsx
    type: table
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/522596/articles/595019/master/file/figures/table_reasons/table_reasons.xlsx"
    folder_url: "/users/522596/articles/595019/master/folder/figures/table_reasons"
    treatFirstLineAsHeader: true
